name: workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: npm install
        working-directory: ./client
        run : npm install

      - name: npm test
        working-directory: ./client
        run : npm test
        
      - name: npm run build
        working-directory: ./client
        run : npm run build

      

